# Site settings
author: Daksha Patel
title: A Developers Diary
header-img: img/home-bg.png
email: dakshapatel100@gmail.com
copyright_name: Daksha Patel
description: > # this means to ignore newlines until "baseurl:"
  Novice to Advanced: A work in progress!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dakshapatel

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
